### ISSUE TITLE
Caught InvalidArgumentException: navigation item '/admin/locations' not found

### ISSUE THREAD

**Issue by tleilax** [Krassmus/LernmodulePlugin#8]
Ich kann mir nicht wirklich erklären geschweige denn reproduzieren, wie es zustande kommt, aber dieser Fehler taucht regelmässig in unseren Logs auf:

```
2022/09/06 12:25:17 [error] 16663#16663: *2525841 FastCGI sent in stderr: "PHP message: Caught InvalidArgumentException: navigation item '/admin/locations' not found in /var/www/studip-5.1/lib/navigation/Navigation.php:126
Stack trace:
#0 /var/www/studip-5.1/lib/navigation/Navigation.php(75): Navigation::getItem('/admin/location...')
#1 /var/www/studip-5.1/public/plugins_packages/RasmusFuhse/LernmodulePlugin/LernmodulePlugin.class.php(49): Navigation::addItem('/admin/location...', Object(Navigation))
#2 [internal function]: LernmodulePlugin->__construct()
#3 /var/www/studip-5.1/lib/plugins/engine/PluginManager.class.php(568): ReflectionClass->newInstance()
#4 /var/www/studip-5.1/lib/plugins/engine/PluginManager.class.php(606): PluginManager->getCachedPlugin(Array)
#5 /var/www/studip-5.1/lib/models/ToolActivation.php(53): PluginManager->getPluginById('335')
#6 /var/www/studip-5.1/lib/models/SimpleCollection.class.php(745): ToolActivation->getStudipModule()
#7 /var/www/studip-5.1/lib/models/SimpleCollection.class.php(761): SimpleCollection->sendMessage('getStudipModule', Array)
#8" while reading response header from upstream, client: 2001:638:705:3f8a::2, server: elearning.uni-oldenburg.de, request: "GET /api.php/zsb/course/9c12585c5e47b062bc50e18677731800? HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "elearning.uni-oldenburg.de"
```

**Comment by Krassmus** [comment]
Ja, so eine Änderung habe ich im Superwiki auch eingebaut, als Nico mich auf die Einträge im Error-Log aufmerksam gemacht hatte. Ich denke, ihr habt irgendwelche Root-Admins im System, die die Admin -> Standorte nicht sehen können. Wieso und warum sie das nicht können, weiß ich auch nicht. Nico meinte, sowas gibt es nicht bei euch. Auch seltsam ist, dass das erst nach dem Update auftaucht, denn diese Fehler hätten auch vor dem Update im Log landen müssen.

**Comment by tleilax** [comment]
Eventuell war das vor dem Update auch schon im Log. Wir achten gerade nur etwas mehr drauf.

Danke für die Änderungen!
